export const OrderErrorCodes = {
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_STATUS_TRANSITION: 'ORDER_INVALID_STATUS_TRANSITION',
  ORDER_TERMINAL_STATE: 'ORDER_TERMINAL_STATE',
  ORDER_MOVE_TARGET_OCCUPIED: 'ORDER_MOVE_TARGET_OCCUPIED',
  ORDER_MOVE_CROSS_BRANCH_NOT_ALLOWED: 'ORDER_MOVE_CROSS_BRANCH_NOT_ALLOWED',
  ORDER_MOVE_NOT_ALLOWED_FOR_TYPE: 'ORDER_MOVE_NOT_ALLOWED_FOR_TYPE',
  ORDER_ALREADY_MERGED: 'ORDER_ALREADY_MERGED',
  ORDER_SCOPE_FORBIDDEN: 'ORDER_SCOPE_FORBIDDEN',
  ORDER_ITEM_MENU_NOT_VISIBLE: 'ORDER_ITEM_MENU_NOT_VISIBLE',
  ORDER_LOCK_TIMEOUT: 'ORDER_LOCK_TIMEOUT',
  ORDER_TABLE_NOT_FOUND: 'ORDER_TABLE_NOT_FOUND',
  ORDER_BAD_REQUEST: 'ORDER_BAD_REQUEST',
} as const;

export type OrderErrorCode =
  (typeof OrderErrorCodes)[keyof typeof OrderErrorCodes];
