export enum RuleKey {
    // CASH Rules
    CASH_CHECK_OPEN_TABLES = 'CASH_CHECK_OPEN_TABLES',

    // ORDER Rules
    ORDER_MANDATORY_TABLE = 'ORDER_MANDATORY_TABLE',
    ORDER_PREVENT_VOID = 'ORDER_PREVENT_VOID',

    // INVENTORY Rules
    INVENTORY_PREVENT_DELETE = 'INVENTORY_PREVENT_DELETE',
    INVENTORY_LOW_STOCK_ALERT = 'INVENTORY_LOW_STOCK_ALERT',

    // MENU Rules
    MENU_PREVENT_DELETE_ITEM = 'MENU_PREVENT_DELETE_ITEM',

    // SYSTEM Rules (Future)
    SYSTEM_MAINTENANCE_MODE = 'SYSTEM_MAINTENANCE_MODE',
}
